---
title: "Encuesta sobre hábitos de estudio"
author: "Jean Paul Yepes"
date: "16 de septiembre de 2020"
output: 
  html_document: 
    toc: yes
    #theme: journal
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)
```

```{r}
datosEncuesta <- read.csv2("Encuesta_habitos.csv", 
                       encoding = "UTF-8",
                       dec = ".",
                       stringsAsFactors = FALSE)
```

```{r}
carreras <- datosEncuesta$carrera
summary(as.factor(carreras))
```

```{r}
library(stringr)
carreras <- str_replace(carreras, regex("est.*", ignore_case = TRUE ), "Estadistica")
carreras <- str_replace(carreras, regex(".*sis.*", ignore_case = TRUE ), "Ingenieria de sistemas")
carreras <- str_replace(carreras, regex(".*fís.*", ignore_case = TRUE ), "Ingenieria fisica")
carreras <- str_replace(carreras, regex(".*adm.*", ignore_case = TRUE ), "Ingenieria administrativa")
carreras <- str_replace(carreras, regex(".*con.*", ignore_case = TRUE ), "Ingenieria de control")
carreras <- str_replace(carreras, regex(".*industrial.*", ignore_case = TRUE ), "Ingenieria industrial")
```

```{r}
datosEncuesta$carrera = carreras
head(datosEncuesta)
```

```{r}
computadorPropio <- datosEncuesta$computador_mesa
summary(as.factor(computadorPropio) )
```


```{r}
computadorPropio <- str_replace(computadorPropio, regex("si.*", ignore_case = TRUE ), "Si")
summary(as.factor(computadorPropio) )
```
```{r}
datosEncuesta$computador_mesa = computadorPropio
print(head(datosEncuesta))
```

```{r}
library(tidyr)
datosEncuesta <- separate(datosEncuesta, col = portatil, into = c("portatil", "De donde"), sep = ",")
```


```{r}
origenCovid <- datosEncuesta$origen_covid_19
origenCovid <- na.omit(origenCovid)
summary(as.factor(origenCovid) )
```


```{r}
library(dplyr)
habitos <- datosEncuesta %>% select(starts_with("habito"))
head(habitos)
```
```{r}
#vect <- unlist(habitos)
vect <- unlist(data.frame(C1 = c(t(habitos)))['C1'] )
#class(vect)
summary(vect)
summary(na.omit(vect))
```

```{r}
fecha_nac1 <- as.Date(datosEncuesta$fecha_nac, "%d/%m/%Y")
fechas_con_problemas <- subset(datosEncuesta, 
                               subset = is.na(fecha_nac1) | 
                                 as.integer(format(fecha_nac1, "%Y")) < 1970, 
                               select = c("consecutivo", "fecha_nac"))

fechas_con_problemas$fecha_nac_correcta <- c("05/09/1999", "08/10/1996",
                                             "06/03/2020", "01/07/1994",
                                             "01/01/2000", "07/10/2003",
                                             "17/09/1992", "12/08/2020",
                                             "12/05/1998", "21/06/1983",
                                             "12/08/2020", "28/09/1956",
                                             "09/06/1999", "10/09/2002",
                                             "20/06/1994")


print(fechas_con_problemas$fecha_nac_correcta)

datosEncuesta$fecha_nac[fechas_con_problemas$consecutivo] <- fechas_con_problemas$fecha_nac_correcta
```


```{r}
#enc_habit$fecha_nac <- as.Date(enc_habit$fecha_nac)
#summary(enc_habit)
```
